[project]
requires-python = "3.9.17"

[tool.poetry]
name = "anki-code-highlighter"
version = "1.1.0"
authors = ["Grzegorz Milka <grzegorzmilka@gmail.com>"]
description = "Anki plugin for code syntax highlighting"
classifiers = [
  "Programming Language :: Python :: 3",
  "License :: OSI Approved :: GNU Affero General Public License v3 or later (AGPLv3+)",
  "Operating System :: OS Independent",
]
license = "AGPLv3"
readme = "README.md"

[tool.poetry.urls]
Repository = "https://github.com/gregorias/anki-code-highlighter"

[tool.poetry.dependencies]
python = "==3.9.17"
anki = "==2.1.65"
aqt = "==2.1.65"
pyqt6 = "==6.3.*"
PyQt6-WebEngine = "==6.3.*"

[tool.poetry.group.dev.dependencies]
bpython = "*"
mypy = "*"
yapf = "*"
cssutils = "*"
types-beautifulsoup4 = "*"
