[project]
requires-python = "==3.9.19"

[tool.poetry]
name = "anki-code-highlighter"
version = "24.3.1"
authors = ["Grzegorz Milka <grzegorzmilka@gmail.com>"]
description = "Anki plugin for code syntax highlighting"
classifiers = [
  "Programming Language :: Python :: 3",
  "License :: OSI Approved :: GNU Affero General Public License v3 or later (AGPLv3+)",
  "Operating System :: OS Independent",
]
license = "AGPLv3"
readme = "README.md"

[tool.poetry.urls]
Repository = "https://github.com/gregorias/anki-code-highlighter"

[tool.poetry.dependencies]
python = "==3.9.19"
anki = "==23.10.*"
aqt = "==23.10.*"
# Use the same version of PyQt6 as Anki:
# https://github.com/ankitects/anki/blob/72e57456ceb1e97a37198d490ea1ca72e38f61f6/python/requirements.qt6_mac.txt#L1
pyqt6 = "==6.5.2"
pyqt6-qt6 = "==6.5.2"
PyQt6-WebEngine = "==6.5.0"
PyQt6-WebEngine-qt6 = "==6.5.2"

[tool.poetry.group.dev.dependencies]
bpython = "*"
mypy = "*"
cssutils = "*"
types-beautifulsoup4 = "*"
webcolors = "*"
